DO
$$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '__APP_DB_USER__') THEN
    CREATE ROLE __APP_DB_USER__ LOGIN PASSWORD '__APP_DB_PASSWORD__';
  ELSE
    ALTER ROLE __APP_DB_USER__ WITH LOGIN PASSWORD '__APP_DB_PASSWORD__';
  END IF;

  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '__N8N_DB_USER__') THEN
    CREATE ROLE __N8N_DB_USER__ LOGIN PASSWORD '__N8N_DB_PASSWORD__';
  ELSE
    ALTER ROLE __N8N_DB_USER__ WITH LOGIN PASSWORD '__N8N_DB_PASSWORD__';
  END IF;
END
$$;

SELECT 'CREATE DATABASE __APP_DB_NAME__ OWNER __APP_DB_USER__'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '__APP_DB_NAME__')
\gexec

SELECT 'CREATE DATABASE __N8N_DB_NAME__ OWNER __N8N_DB_USER__'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '__N8N_DB_NAME__')
\gexec

GRANT ALL PRIVILEGES ON DATABASE __APP_DB_NAME__ TO __APP_DB_USER__;
GRANT ALL PRIVILEGES ON DATABASE __N8N_DB_NAME__ TO __N8N_DB_USER__;
